### PR TITLE
Fix the images paths in the 100-account.md

### PR DESCRIPTION
**Pull request by pablogarciaarevalo**
Fix the images path with the same folder instead of the parent folder

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rezabekf** [comment]
Thank you for the patch, I will review this tomorrow and merge once the tests pass.
Cheers Franco

**Comment by rezabekf** [comment]
Hello, the markdown used for this workshop is using Hugo short-codes. Unfortunately, Hugo short-codes aren't supported in GitHub and I would suggest to use [official workshop website](https://cfn101.sa.engineering/), which renders links and images correctly.

At this point, I can not merge this PR into the `master` as it would break the web site.

Thanks,
Franco

**Review by rezabekf — COMMENTED** [review]
Hello, the markdown used for this workshop is using Hugo short-codes. Unfortunately, Hugo short-codes aren't supported in GitHub and I would suggest to use [official workshop website](https://cfn101.sa.engineering/), which renders links and images correctly. More info on official Hugo support [page](https://discourse.gohugo.io/t/image-path-with-relative-urls/21970)

At this point, I can not merge this PR into the `master` as it would break the web site.

Thanks,
Franco

**Comment by pablogarciaarevalo** [comment]
Hello Franco.

It seems that it works in the .sa.engineering domain but not in the workshop.aws.

- It works: https://cfn101.sa.engineering/30-workshop-part-01/10-cloudformation-fundamentals/
- It does not work: https://cfn101.workshop.aws/30-workshop-part-01/10-cloudformation-fundamentals.html

Regards,
Pablo

**Comment by rezabekf** [comment]
Great find, I wasn't aware, that the workshop has been already moved to official AWS workshop site. I will contact the owner of the domain. This is most likely issue with outdated Hugo framework within the AWS Amplify service. I will reopen this as an issue.

**Pull request closed without merging**
