### PR TITLE
Add cloud9 instructions to user-data page

### PR DESCRIPTION
**Pull request by cjhar**
## What does this PR do and why?

Updated instructions to use Cloud9 and aws cfn deploy of local template

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [X] Pre-commit checks passed.
- [X] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cjhar** [comment]
Ready for review, thanks!

**Review by rezabekf — CHANGES_REQUESTED** [review]
Little changes to make it consistent.

**Comment by cjhar** [comment]
Thank you for review and suggestions, all incorporated and updated sample images. Estimated timing confirmed.

**Tested end2end**

**Review by rezabekf — APPROVED** [review]
Approved.

**Pull request merged**
