### PR TITLE
Translated workshop top page in Japanese

### PR DESCRIPTION
**Pull request by cmick-aws**
To : tkimurz
Please review Japanese translation and approve PR, do not merge.

To : AWS UK Solution Builder
Please wait for review to complete before merging.
No need to update verson until merging to main branch.

### CODE REVIEW

**Comment by tkimurz** [comment]
To: @cmick-aws 
This looks good, approved.

**Review by tkimurz — COMMENTED** [review]
This looks good.

**Review by tkimurz — APPROVED** [review]
This looks good.

**Review by rezabekf — APPROVED** [review]
All good 👍

**Pull request merged**
